### ISSUE TITLE
Angular 2 example

### ISSUE THREAD

**Issue by Abrissirba** [David-Mulder/paper-datatable#70] opened 2015-12-28 15:19 UTC
I'm building an app with angular 2 and am currently using paper elements as my GUI component library. I have succeeded to integrate the official elements but can't get paper-datatable to work for some reason. Would be really nice to see an example of paper-datable together with angular 2 if it is possible.

**Comment by David-Mulder** [comment] 2015-12-29 08:41
@Abrissirba With Angular, shouldn't you use the Angular Material elements instead of the Polymer elements? Of course in theory nothing is stopping you from mixing the two, but in general that's a pretty bad idea. Either way, in Angular there is `md-data-table` by Daniel Nagy which lacks a lot of the features that this `paper-datatable` provides, but at least it's written in and meant for Angular.

**Comment by Abrissirba** [comment] 2015-12-29 08:53
You are absolutely right that Angular Material is the better choice if you are developing in Angular 1.X.X. However, Angular 2 is now in beta and Angular Material has not been upgraded to this yet. One of the design goals with Angular 2 has been to make it work togheter with web components. Since Angular 2 still is in beta there are not many GUI libraries out yet that is written explicitly for Angular 2 so I have been playing around with polymer so far. This have been working quite well so far but since Polymer lacks a datatable I tried paper-datatable since it seems to be exactly what I'm looking for, feature wise, but I can't get it to work. 

The error I get is 'Cannot set property '_pdt_getArrayItemLabel' of undefined in paper-datatable-column.html row 424. One guees I have to way it isn't working is that I'm using angular 2 templates and not a polymer template.

**Comment by David-Mulder** [comment] 2015-12-29 09:20
@Abrissirba Ah, now that's an error I can help with. The issue is related to the undocumented and somewhat unreliable `dataHost` property. I presume you're getting a warning on the console above that error with a line saying 'A hack is used to support some functionality of the `[editable]` and [`array-display-prop`] attribute. This however requires the element to be located in a polymer element or `dom-bind`.'? 

If so then my suggested solution would be to first try and place the element in a dummy `dom-bind` (`<template is="dom-bind"></template>`). It's a bit ugly, but it might just work. Or alternatively you might try putting [these two lines](https://github.com/David-Mulder/paper-datatable/blob/master/paper-datatable-column.html#L424) in to a `if(typeof this.dataHost !== 'undefined')` provided you're not using `[editable]` without custom `<template>`'s.

And yes, this part of the component is a bit hacky to ensure a natural development flow in Polymer, but I am not entirely sure how this would look in combination with Angular 2. Normally in Polymer you can call functions from your bindings inside the custom templates as well which are to be defined in the host scope and `dataHost` is supposed to refer to that, however an orphan element without such a host is a bit harder to figure out.

**Comment by Abrissirba** [comment] 2015-12-30 21:46
Being new to polymer I'm struggling a bit to find out why things doesn't work as I intend so be prepared for stupid questions since I don't know how Polymer is supposed to work and if Angular 2 is what's causing my errors. I'm having trouble custom columns. I have the following paper-datatable-card which mixes some angular 2 and polymer. 

``` html
<paper-datatable-card header="Page" property="page" [dataSource]="dataSource">
      <paper-datatable (onRowTap)="rowTapped">
            <paper-datatable-column header="Title" property="title" sortable>
                <template>
                    <span id="title" (click)="clicked()">test</span>
                </template>
            </paper-datatable-column>
      </paper-datatable>
</paper-datatable-card>
```

The table renders all the rows returned from my datasource but it uses the default renderer which will print the title property instead of my custom template which is hard coded to print hej.

If I put a breakpoint in the created callback of paper-datatable-column and look at the node I get 

``` html
<paper-datatable-column header="Title" property="title" sortable=""  _ngcontent-quh-6="">
       <!--template bindings={}-->
</paper-datatable-column>
```

Compared with what the demo shows in the same callback

``` html
<paper-datatable-column header="Name" property="name" type="Object" tooltip="Some title" sortable="" style="min-width: 160px">
     <template>
         #document-fragment
     </template>
</paper-datatable-column>
```

When I look at the node in the ready callback, my custom template node is completely gone.

Do you have any idea what might causing this?

**Comment by s-devaney** [comment] 2016-01-02 00:07
I've been trying to use this with Backbone and encountered similar problems. My issue was with the way that Backbone renders views (element by element, top down) which means the Polymer shadow DOM doesn't get initialized properly.

For some (simpler) elements this can be fixed by overriding the render methods to use the Polymer API to set the shadow DOM properly (Polymer.dom.appendChild). 

For this element that particular method didn't work. I managed to get it working by creating a custom element which set up the data-table within it's template. I then added methods to interface between the Backbone view (i.e. set data, etc) and the data-table element.

As stated by @David-Mulder above, Polymer elements aren't supposed to be used like this and most Polymer elements suffer from similar issues.

**Comment by danieleds** [comment] 2016-02-04 16:05
I have the same problem with Angular 2...

@Abrissirba did you find a way to fix it?

@David-Mulder I **don't** get the message `console.warn('A hack is used to support some functionality of...`, there is only `Cannot set property '_pdt_getArrayItemLabel' of undefined...`

**Comment by Abrissirba** [comment] 2016-02-04 17:55
No, I didn't find any solution to it which maid me turn away from angular2 together with polymer.

**Comment by allenmoatallen** [comment] 2016-02-25 15:38
@danieleds @David-Mulder The reason we aren't receiving the console warning under Angular2 is because within the `_registerEvilFunctions` function `this.parentNodeRef.dataHost` is undefined but the if statement doesn't check that it isn't undefined, it tries to set `this.dataHost` to `this.parentNodeRef.dataHost`. 

This is at lines 416 - 422 within paper-datatable-column. As a side note I couldn't get the paper-datatable-card to show any data, but using plain `paper-datatable` with the `data` attribute worked for me but the table wasn't styled at all.

**Comment by bluEEil** [comment] 2016-04-26 09:55
I just got the same issue while working on angular 2.

wrapping my table html with <template is="dom-bind"></template> didnt work (the table wasnt even shown). I do need the editing so putting thoose lines under the if is not an option. my own temporary solution was defining a polymer component that only wraps the paper-table. Im having some difficulity to write this wrapper as im not very experienced with polymer (and I need to find ways to pass all attributes in embed html from the wrapper to the table) 
any ideas on how I can make this wrapper work good or maybe there are other available solutions to this in present time?

I tried 2 solutions which didn't work yet, I have explained them in this questetion that I just posted on stackoverflow:
[http://stackoverflow.com/questions/36864501/using-paper-datatable-in-angular2](url)

> If so then my suggested solution would be to first try and place the element in a dummy dom-bind (<template is="dom-bind"></template>). It's a bit ugly, but it might just work. Or alternatively you might try putting these two lines in to a if(typeof this.dataHost !== 'undefined') provided you're not using [editable] without custom <template>'s.

**Comment by bluEEil** [comment] 2016-05-30 08:46
@Abrissirba @David-Mulder @danieleds 
I think I managed to get to some solution. I altered small parts of the source code, this might 
"hurt" some features (I think only the ones related to the column array) but I work with it in my project and it works great. I also wrote a small angular 2 component wrapper to ease things up.
You can check it out here:
https://github.com/bluEEil/paper-datatable-fixes-for-angular-2

**Closed as completed** 2017-05-24 18:40 UTC
Labels: question
